// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardContainer: typeof import('./src/components/common/CardContainer/CardContainer.vue')['default']
    CardPopUp: typeof import('./src/components/common/PopUp/CardPopUp.vue')['default']
    ContentCard: typeof import('./src/components/common/ContentCard/ContentCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FooterBar: typeof import('./src/components/FooterBar/FooterBar.vue')['default']
    HeaderCard: typeof import('./src/components/HeaderCard/HeaderCard.vue')['default']
    HeaderCardNav: typeof import('./src/components/HeaderCard/HeaderCardNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
